/*
 * GridFindDialog.java
 *
 * Created on December 3, 2006, 11:29 AM
 */

package com.exalto.UI.util;

import com.exalto.UI.grid.ActionsHandler;
import com.exalto.UI.grid.JXmlTreeTable;

import org.jdesktop.swingx.JXCollapsiblePane;
import org.jdesktop.swingx.search.Searchable;
import org.jdesktop.swingx.search.AbstractSearchable;


//OM import com.exalto.UI.grid.xpath.JAXPXPathEvaluator;
import javax.swing.AbstractButton;
import javax.swing.JComponent;
import javax.swing.JTable;

import java.util.regex.Pattern;

/**
 *
 * @author  sys
 */
public class GridFindDialog extends javax.swing.JFrame {

    private Searchable searchable;
    private JXCollapsiblePane collapsible;
    int startIndex = -1;
    JTable table;
    com.exalto.UI.util.SearchExtnForm searchExtnForm;
    
    /** Creates new form GridFindDialog */
    public GridFindDialog(java.awt.Frame parent, boolean modal, JComponent target, Searchable searchable) {
     //   super(parent, modal);
        this.searchable = searchable;
        initComponents();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        // OV c 27/05/08 for June rel TODO:  
        //        searchExtnForm = new SearchExtnForm(this);
    
        // OV c 27/05/08 for June rel TODO:  
  //      jXCollapsiblePane1.add(searchExtnForm);
        
        
   //     jXCollapsiblePane1.setCollapsed(true);
        
        try {

      //OM240815      String pattern = ((AbstractSearchable) searchable).getPattern();
			
			String pattern = "";
			
			//         jbinit();
            
            if(pattern != null)
                jTextField1.setText(pattern);
	            
            this.searchable = searchable;        
            if(target instanceof JTable) {
    		this.table = (JTable) target;
		//		startIndex = table.getSelectedRow();
			
                  // 	System.out.println(" startIndex dlg =  " + startIndex);
	    }
            
            if(target instanceof Expandable) {
                Expandable expandable = (Expandable) target;
		//		startIndex = table.getSelectedRow();
			
                // 	System.out.println(" startIndex dlg =  " + startIndex);
            	expandable.expandAll();
          
            }    
            
                show();
        } catch(Exception e) {
            e.printStackTrace();
        }
 
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        insertMenu = new javax.swing.JMenu();
        insElemItem = new javax.swing.JMenuItem();
        insAttrItem = new javax.swing.JMenuItem();
        insTextItem = new javax.swing.JMenuItem();
        deleteMenu = new javax.swing.JMenu();
        delEmenItem = new javax.swing.JMenuItem();
        delAttrItem = new javax.swing.JMenuItem();
        delTextItem = new javax.swing.JMenuItem();
        renameMenu = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        cutItem = new javax.swing.JMenuItem();
        copyItem = new javax.swing.JMenuItem();
        pasteItem = new javax.swing.JMenuItem();
        undoItem = new javax.swing.JMenuItem();
        redoItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        expandItem = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jFind = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jXCollapsiblePane1 = new JXCollapsiblePane();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("exalto/xmlgrid"); // NOI18N
        insertMenu.setText(bundle.getString("grid.insert")); // NOI18N

        insElemItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        insElemItem.setMnemonic(java.util.ResourceBundle.getBundle("exalto/xmlgrid").getString("grid.insert.element.mnemonic").charAt(0));
        insElemItem.setText(bundle.getString("grid.insert.element")); // NOI18N
        insElemItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertElementClicked(evt);
            }
        });
        insertMenu.add(insElemItem);

        insAttrItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        insAttrItem.setMnemonic(java.util.ResourceBundle.getBundle("exalto/xmlgrid").getString("grid.delete.element.mnemonic").charAt(0));
        insAttrItem.setText(bundle.getString("grid.insert.attr")); // NOI18N
        insAttrItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertAttrClicked(evt);
            }
        });
        insertMenu.add(insAttrItem);

        insTextItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        insTextItem.setMnemonic(java.util.ResourceBundle.getBundle("exalto/xmlgrid").getString("grid.rename.mnemonic").charAt(0));
        insTextItem.setText(bundle.getString("grid.insert.text")); // NOI18N
        insTextItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertTextClicked(evt);
            }
        });
        insertMenu.add(insTextItem);

        jPopupMenu1.add(insertMenu);

        deleteMenu.setText(bundle.getString("grid.delete")); // NOI18N

        delEmenItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        delEmenItem.setMnemonic(java.util.ResourceBundle.getBundle("exalto/xmlgrid").getString("grid.delete.element.mnemonic").charAt(0));
        delEmenItem.setText(bundle.getString("grid.insert.element")); // NOI18N
        delEmenItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteElementClicked(evt);
            }
        });
        deleteMenu.add(delEmenItem);

        delAttrItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        delAttrItem.setMnemonic(java.util.ResourceBundle.getBundle("exalto/xmlgrid").getString("grid.delete.attr.mnemonic").charAt(0));
        delAttrItem.setText(bundle.getString("grid.insert.attr")); // NOI18N
        delAttrItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAttrClicked(evt);
            }
        });
        deleteMenu.add(delAttrItem);

        delTextItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        delTextItem.setMnemonic(java.util.ResourceBundle.getBundle("exalto/xmlgrid").getString("grid.delete.text.mnemonic").charAt(0));
        delTextItem.setText(bundle.getString("grid.insert.text")); // NOI18N
        delTextItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTextClicked(evt);
            }
        });
        deleteMenu.add(delTextItem);

        jPopupMenu1.add(deleteMenu);

        renameMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        renameMenu.setMnemonic(java.util.ResourceBundle.getBundle("exalto/xmlgrid").getString("grid.rename.mnemonic").charAt(0));
        renameMenu.setText(bundle.getString("grid.rename")); // NOI18N
        renameMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameElemClicked(evt);
            }
        });
        jPopupMenu1.add(renameMenu);
        jPopupMenu1.add(jSeparator1);

        cutItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        cutItem.setText(bundle.getString("grid.cut")); // NOI18N
        jPopupMenu1.add(cutItem);

        copyItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        copyItem.setText(bundle.getString("grid.copy")); // NOI18N
        jPopupMenu1.add(copyItem);

        pasteItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        pasteItem.setText(bundle.getString("grid.paste")); // NOI18N
        jPopupMenu1.add(pasteItem);

        undoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        undoItem.setText(bundle.getString("grid.undo")); // NOI18N
        jPopupMenu1.add(undoItem);

        redoItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        redoItem.setText(bundle.getString("grid.redo")); // NOI18N
        redoItem.setPreferredSize(new java.awt.Dimension(59, 19));
        jPopupMenu1.add(redoItem);
        jPopupMenu1.add(jSeparator2);

        expandItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        expandItem.setText(bundle.getString("grid.expand")); // NOI18N
        expandItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expandAllClicked(evt);
            }
        });
        jPopupMenu1.add(expandItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("grid.search.title")); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        jFind.setText(bundle.getString("Find.label")); // NOI18N

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                findFocusLost(evt);
            }
        });

        jButton6.setText(bundle.getString("grid.search.button.find")); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText(bundle.getString("grid.search.button.close")); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jToggleButton2.setText(bundle.getString("grid.search.button.more")); // NOI18N
        jToggleButton2.setEnabled(false);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("String");
        jRadioButton3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton3StateChanged(evt);
            }
        });
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("XPath");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jLabel3.setText("Search Type:");

        jCheckBox3.setText("    Match backwards");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(40, 40, 40)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCheckBox3)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jFind)
                                .add(37, 37, 37)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(12, 12, 12)
                                        .add(jRadioButton3)
                                        .add(18, 18, 18)
                                        .add(jRadioButton4))))
                            .add(jLabel3))
                        .add(33, 33, 33)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton7)
                            .add(jToggleButton2)
                            .add(jButton6))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jFind)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton6))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                        .add(jButton7)
                        .add(15, 15, 15)
                        .add(jToggleButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel3)
                            .add(jRadioButton3)
                            .add(jRadioButton4))
                        .add(18, 18, 18)
                        .add(jCheckBox3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .add(11, 11, 11))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);
        jPanel1.getAccessibleContext().setAccessibleParent(this);

        jXCollapsiblePane1.setCollapsed(true);
        getContentPane().add(jXCollapsiblePane1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_findFocusLost
// TODO add your handling code here:
        
    }//GEN-LAST:event_findFocusLost

    private void expandAllClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expandAllClicked
// TODO add your handling code here:
    }//GEN-LAST:event_expandAllClicked

    private void renameElemClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameElemClicked
// TODO add your handling code here:
    }//GEN-LAST:event_renameElemClicked

    private void deleteTextClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTextClicked
// TODO add your handling code here:
    }//GEN-LAST:event_deleteTextClicked

    private void deleteAttrClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAttrClicked
// TODO add your handling code here:
    }//GEN-LAST:event_deleteAttrClicked

    private void deleteElementClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteElementClicked
// TODO add your handling code here:
    }//GEN-LAST:event_deleteElementClicked

    private void insertTextClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertTextClicked
// TODO add your handling code here:
    }//GEN-LAST:event_insertTextClicked

    private void insertAttrClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertAttrClicked
// TODO add your handling code here:
    }//GEN-LAST:event_insertAttrClicked

    private void insertElementClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertElementClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_insertElementClicked

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
// TODO add your handling code here:
  //      System.out.println(" sel trow - " + treeTable.getSelectedRow());
  //      System.out.println(" sel tcol - " + treeTable.getSelectedColumn());
        
        if (evt.isPopupTrigger()) {
                jPopupMenu1.show(evt.getComponent(), evt.getX(), evt.getY());
                return;
          }
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
// TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
// TODO add your handling code here:
                	  AbstractButton abstractButton = (AbstractButton) evt.getSource();
			  boolean selected = abstractButton.getModel().isSelected();
				System.out.println("Action - selected=" + selected + "\n");

        				if(selected) {
					System.out.println(" in SHOWMOREOPTIONS");
                                        jXCollapsiblePane1.add(searchExtnForm);
                                	jXCollapsiblePane1.setCollapsed(false);
                                        pack();
                                   //     jToggleButton2.setActionCommand(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("grid.search.button.less"));         
                                  
				} else {
					System.out.println(" collapsing... ");
                                        jXCollapsiblePane1.remove(searchExtnForm);
					jXCollapsiblePane1.setCollapsed(true);
                                //        jToggleButton2.setActionCommand(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("grid.search.button.more"));         
                                        pack();
                          	}

    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.cancelButtonPressed();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        stringSelected();
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton3StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3StateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        findButtonPressed();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        if(this.jCheckBox3.isSelected())
            jCheckBox3.setSelected(false);
        xpathSelected();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        if(this.jRadioButton4.isSelected()) {
            jRadioButton3.setSelected(true);
            jRadioButton4.setSelected(false);
        }

    }//GEN-LAST:event_jCheckBox3ActionPerformed
/*
    private void jbinit() {
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
 //       jButton5 = new javax.swing.JButton();
         Action moreAction = new AbstractAction("More Options") {
		  public void actionPerformed(ActionEvent e) {
			// show find panel

			  AbstractButton abstractButton = (AbstractButton) e.getSource();
			  boolean selected = abstractButton.getModel().isSelected();
				System.out.println("Action - selected=" + selected + "\n");

				if(selected) {
					System.out.println(" in SHOWMOREOPTIONS");
				jXCollapsiblePane1.setCollapsed(false);
				} else {
					System.out.println(" collapsing... ");
					jXCollapsiblePane1.setCollapsed(true);
				}


		  }
		};


 
        jButton5 = new javax.swing.JToggleButton(moreAction);
 
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
  //      jLabel1.setText("jLabel1");
        jLabel1.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("Find.label"));

        jTextField1.setText("jTextField1");

    //    jLabel2.setText("jLabel2");
        jLabel2.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("Replace.label"));

        jTextField2.setText("jTextField2");

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox2.setText("jCheckBox2");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton1.setText("Find Next");

        jButton2.setText("Replace");

        jButton3.setText("Replace All");

        jButton4.setText("Close");

        jButton5.setText(" More Options");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());

		Container ctr = getContentPane();
        ctr.setLayout(new BorderLayout());


		JPanel form = new JPanel();

		form.setLayout(new GridLayout(3,2));

       		form.add(jTextField1);
		form.add(jTextField1);
		form.add(jButton1);

		form.add(jTextField2);
		form.add(jButton2);

		form.add(jCheckBox1);
		form.add(jButton5);

		collapsible = new JXCollapsiblePane();
		
		//GridOptions gops = new GridOptions();
	
	    JPanel controls = new JPanel(new FlowLayout(FlowLayout.LEFT, 4, 0));
		controls.add(new JLabel("Search:"));
		controls.add(new JTextField(10));
	 	controls.add(new JButton("Refresh"));
		collapsible.add("Center", controls);
		collapsible.setCollapsed(true);
	
		ctr.add(form, BorderLayout.CENTER);
		ctr.add(collapsible, BorderLayout.SOUTH);

		
		pack();
   
    }
*/        
    	private void findButtonPressed() {
	
		String searchtext = jTextField4.getText();
		// ov commented 25/3/05		
		// editor.search( searchtext, jcbMatchCase.isSelected(), jrbDown.isSelected());		
	//	editor.search( searchtext, matchCase, searchDirection, matchWord, false, null, false);		


        boolean backwards = this.jCheckBox3.isSelected();

        int foundIndex = 0;
        if(!backwards) {
            if(this.searchType.equals("string"))
                foundIndex = searchable.search(searchtext);
            else {

                if(table instanceof JXmlTreeTable) {
                    JXmlTreeTable treeTable =  (JXmlTreeTable) table;
                    
                    ActionsHandler ah = treeTable.getActionsHandler();
                    
            //OM        JAXPXPathEvaluator xpe = new JAXPXPathEvaluator(treeTable, ah);

            //OM        xpe.evaluate(searchtext, true);

                }
            }
                
        } else {
            if(this.searchType.equals("string"))
               foundIndex = searchable.search(searchtext, -1, backwards);
            

        }
      
	//	setVisible( false); 
	}

   private void stringSelected() {
       searchType = "string";
   }

   private void xpathSelected() {

       searchType = "xpath";
   }
   	private void cancelButtonPressed() {
		setVisible( false);
	}

	private void replaceButtonPressed() {
		
			String searchtext = jTextField1.getText();	
			String replacetext = jTextField2.getText();	
			
		//	editor.search( searchtext, matchCase, searchDirection, matchWord, true, replacetext, false);
		    int foundIndex = searchable.search(searchtext);
		//	setVisible(false); 
	}

    	public Searchable getSearchable() {
		return searchable;
	}
    
        	private void tryMatch() {
	/*
		if (jrbUp.isSelected()) {
			System.out.println(" Up selected ");
			searchDirection = false;
		} else if(jrbDown.isSelected()) {
			System.out.println(" Down selected ");
			searchDirection = true;
		} else if(jcbWholeWords.isSelected()) {
			System.out.println(" matchWord selected ");
			matchWord = true;
		} else if(!jcbWholeWords.isSelected()) {
			System.out.println(" matchWord unselected ");
			matchWord = false;
		} else if(jcbMatchCase.isSelected()) {
			System.out.println(" Down selected ");
			matchCase = true;
		} else if(!jcbMatchCase.isSelected()) {
			matchCase = false;
		}
            */    
	
	
	}
	

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       /* 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GridFindDialog(null).setVisible(true);
            }
        });
        */
    }

    String searchType = "xpath";
    
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JToggleButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenuItem copyItem;
    private javax.swing.JMenuItem cutItem;
    private javax.swing.JMenuItem delAttrItem;
    private javax.swing.JMenuItem delEmenItem;
    private javax.swing.JMenuItem delTextItem;
    private javax.swing.JMenu deleteMenu;
    private javax.swing.JMenuItem expandItem;
    private javax.swing.JMenuItem insAttrItem;
    private javax.swing.JMenuItem insElemItem;
    private javax.swing.JMenuItem insTextItem;
    private javax.swing.JMenu insertMenu;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jFind;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton2;
    private org.jdesktop.swingx.JXCollapsiblePane jXCollapsiblePane1;
    private javax.swing.JMenuItem pasteItem;
    private javax.swing.JMenuItem redoItem;
    private javax.swing.JMenuItem renameMenu;
    private javax.swing.JMenuItem undoItem;
    // End of variables declaration//GEN-END:variables
    
}
