/*
 * TableFindDlg.java
 *
 * Created on June 3, 2004, 1:44 PM
 */

package com.exalto.UI.util;

import javax.swing.JComponent;
import javax.swing.JTable;
import com.exalto.UI.util.Searchable;
import com.exalto.UI.util.Expandable;

/**
 *
 * @author  sys
 */
public class TableFindDlg extends javax.swing.JDialog {

    private Searchable searchable;
	int startIndex = -1;
	JTable table;
    
    /** Creates new form TableFindDlg */
   public TableFindDlg(java.awt.Frame parent, boolean modal, JComponent target, Searchable searchable) {
           super(parent, modal);
        
        try {
            String pattern = searchable.getSearchPattern();

			
            initComponents();
            
            if(pattern != null)
	            jtfPhrase.setText(pattern);
	            
            this.searchable = searchable;        
            if(target instanceof JTable) {
				this.table = (JTable) target;
		//		startIndex = table.getSelectedRow();
			
          // 	System.out.println(" startIndex dlg =  " + startIndex);
			}
            
            if(target instanceof Expandable) {
				Expandable expandable = (Expandable) target;
		//		startIndex = table.getSelectedRow();
			
          // 	System.out.println(" startIndex dlg =  " + startIndex);
          
          		expandable.expandAll();
          
			}
            
            show();
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        JSrchModeGrp = new javax.swing.ButtonGroup();
        JSrchDirecGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jtfPhrase = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfReplace = new javax.swing.JTextField();
        jcbMatchCase = new javax.swing.JCheckBox();
        jcbWholeWords = new javax.swing.JCheckBox();
        jrbDown = new javax.swing.JRadioButton();
        jrbUp = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jbtnFindNext = new javax.swing.JButton();
        jbtnReplace = new javax.swing.JButton();
        jbtnReplaceAll = new javax.swing.JButton();
        jbtnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.find.title"));
        jLabel1.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.search.text"));

        jLabel2.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.text.replace"));

        jcbMatchCase.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.match.case"));
        jcbMatchCase.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jcbMatchCase.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jcbWholeWords.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.whole.word"));
        jcbWholeWords.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jcbWholeWords.setMargin(new java.awt.Insets(0, 0, 0, 0));

        JSrchDirecGrp.add(jrbDown);
        jrbDown.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.search.forward"));
        jrbDown.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbDown.setMargin(new java.awt.Insets(0, 0, 0, 0));

        JSrchDirecGrp.add(jrbUp);
        jrbUp.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.search.backward"));
        jrbUp.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbUp.setMargin(new java.awt.Insets(0, 0, 0, 0));

        JSrchModeGrp.add(jRadioButton3);
        jRadioButton3.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.search.mode.filter"));
        jRadioButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jLabel3.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.search.mode"));

        JSrchModeGrp.add(jRadioButton4);
        jRadioButton4.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.search.mode.highlight"));
        jRadioButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        JSrchModeGrp.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.search.mode.search"));
        jRadioButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jbtnFindNext.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.find.next"));
        jbtnFindNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFindNextActionPerformed(evt);
            }
        });

        jbtnReplace.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.find.replace"));
        jbtnReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReplaceActionPerformed(evt);
            }
        });

        jbtnReplaceAll.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.find.replaceall"));
        jbtnReplaceAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReplaceAllActionPerformed(evt);
            }
        });

        jbtnClose.setText(java.util.ResourceBundle.getBundle("resources/xmlgrid").getString("table.find.close"));
        jbtnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCloseActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jcbWholeWords)
                    .add(jcbMatchCase)
                    .add(jLabel3)
                    .add(jRadioButton3))
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jrbUp)
                            .add(jrbDown, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jtfPhrase, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .add(layout.createSequentialGroup()
                                        .add(jtfReplace, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))))
                        .add(18, 18, 18)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jbtnFindNext)
                            .add(jbtnReplaceAll)
                            .add(jbtnClose)
                            .add(jbtnReplace)))
                    .add(layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jRadioButton4)
                        .add(46, 46, 46)
                        .add(jRadioButton5)
                        .add(92, 92, 92)))
                .add(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jtfPhrase, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jbtnFindNext))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jtfReplace, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jbtnReplace))
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jcbMatchCase)
                            .add(jrbDown)
                            .add(jbtnReplaceAll))
                        .add(8, 8, 8)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jcbWholeWords)
                            .add(jrbUp))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3))
                    .add(layout.createSequentialGroup()
                        .add(30, 30, 30)
                        .add(jbtnClose)))
                .add(11, 11, 11)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton3)
                    .add(jRadioButton4)
                    .add(jRadioButton5))
                .addContainerGap())
        );
        
        pack();
        
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCloseActionPerformed
// TODO add your handling code here:
        setVisible( false);
        
        searchable.mustReset(true);
        
        
    }//GEN-LAST:event_jbtnCloseActionPerformed

    private void jbtnReplaceAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReplaceAllActionPerformed
// TODO add your handling code here:
        int counter = 0;

        System.out.println(" in replaceAllButtonPressed");

        String searchtext = jtfPhrase.getText();	
        String replacetext = jtfReplace.getText();	
        // editor.searchIndex = -1;

        int foundIndex = searchable.search(searchtext);				
//	editor.search( searchtext, matchCase, searchDirection, matchWord, true, replacetext, true);
//	JOptionPane.showMessageDialog(m_owner, counter+" replacement(s) have been done", HtmlProcessor.APP_NAME, JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jbtnReplaceAllActionPerformed

    private void jbtnReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReplaceActionPerformed
// TODO add your handling code here:
        String searchtext = jtfPhrase.getText();	
        String replacetext = jtfReplace.getText();	

    //	editor.search( searchtext, matchCase, searchDirection, matchWord, true, replacetext, false);
        int foundIndex = searchable.search(searchtext);

    }//GEN-LAST:event_jbtnReplaceActionPerformed

    private void jbtnFindNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFindNextActionPerformed
// TODO add your handling code here:
        
        String searchtext = jtfPhrase.getText();
	// ov commented 25/3/05		
	// editor.search( searchtext, jcbMatchCase.isSelected(), jrbDown.isSelected());		
	//	editor.search( searchtext, matchCase, searchDirection, matchWord, false, null, false);		
	

// OV commented for incorrect behavior	
//		startIndex = table.getSelectedRow();			
		startIndex = searchable.getSearchResultRow();
        System.out.println(" startIndex dlg =  " + startIndex);
		
		int foundIndex = searchable.search(searchtext, startIndex);

    }//GEN-LAST:event_jbtnFindNextActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableFindDlg(new javax.swing.JFrame(), true, null, null).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup JSrchDirecGrp;
    private javax.swing.ButtonGroup JSrchModeGrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JButton jbtnClose;
    private javax.swing.JButton jbtnFindNext;
    private javax.swing.JButton jbtnReplace;
    private javax.swing.JButton jbtnReplaceAll;
    private javax.swing.JCheckBox jcbMatchCase;
    private javax.swing.JCheckBox jcbWholeWords;
    private javax.swing.JRadioButton jrbDown;
    private javax.swing.JRadioButton jrbUp;
    private javax.swing.JTextField jtfPhrase;
    private javax.swing.JTextField jtfReplace;
    // End of variables declaration//GEN-END:variables
    
}
